#CULLALGO
paths:
  fasta: /home/user/your.fasta
  output: /home/user/out-put/directory
  thermo: /home/s_tristan/externals/CULLALGO/v2_test/TSP

#Will you be running solubility with the NetsolP?
run_solubility: Y  # Options are 'Y' or 'N'
external_solubility_path: /path/to/external/solubility.csv  # Only used if run_solubility is 'N'


#The number of sequences you want the program to output after culling.
num_sequences: 500

#How much does each of these weights matter: 1 - Doesn't matter, 2 - Matters somewhat, 3 - Paramount
weights:
  Molecular_Weight: 3
  ASA: 3
  Isoelectric_Point: 3
  Cost: 3
  Solubility: 3
  Thermostability: 3
  Num_Alpha_Helices: 3
  Entropy: 3
  DNA_Complexity: 3